import path from 'path';
import { defineConfig } from 'vite';
import { readdirSync, existsSync } from 'fs';

// Get all HTML files for multi-page app build
const getHtmlEntries = () => {
  const entries: Record<string, string> = {};

  // Root HTML files
  const htmlFiles = readdirSync('.').filter(
    f =>
      f.endsWith('.html') &&
      !f.includes('backup') &&
      f !== 'roadmap.html' &&
      f !== 'navbar-component.html',
  );
  htmlFiles.forEach(file => {
    const name = file.replace('.html', '');
    entries[name] = path.resolve(__dirname, file);
  });

  // Admin folder
  if (existsSync('./admin/index.html')) {
    entries['admin/index'] = path.resolve(__dirname, 'admin/index.html');
  }

  // Blog posts (generated by build:blog script)
  if (existsSync('./blog')) {
    const blogFiles = readdirSync('./blog').filter(f => f.endsWith('.html'));
    blogFiles.forEach(file => {
      const name = file.replace('.html', '');
      entries[`blog/${name}`] = path.resolve(__dirname, 'blog', file);
    });
  }

  return entries;
};

export default defineConfig(() => {
    return {
      server: {
        port: 3000,
        host: '0.0.0.0',
      },
      plugins: [],
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '.'),
        }
      },
      build: {
        // Multi-page app support
        rollupOptions: {
          input: getHtmlEntries(),
          output: {
            // Chunk naming for better caching
            chunkFileNames: 'assets/js/[name]-[hash].js',
            entryFileNames: 'assets/js/[name]-[hash].js',
            assetFileNames: (assetInfo) => {
              const ext = assetInfo.name?.split('.').pop() || '';
              if (/png|jpe?g|svg|gif|webp|avif/i.test(ext)) {
                return 'assets/images/[name]-[hash][extname]';
              }
              if (/css/i.test(ext)) {
                return 'assets/css/[name]-[hash][extname]';
              }
              return 'assets/[name]-[hash][extname]';
            },
          },
        },
        // Minification
        minify: 'terser',
        terserOptions: {
          compress: {
            drop_console: true,
            drop_debugger: true,
          },
        },
        // CSS optimization
        cssMinify: true,
        // Source maps for debugging (optional, disable for smaller builds)
        sourcemap: false,
        // Output directory
        outDir: 'dist',
        // Clean output directory before build
        emptyOutDir: true,
      },
    };
});
